### YamlMime:Yaml
#ms.openlocfilehash: 32819343100f4d8212e660497c1dd9a1e652711a
#ms.sourcegitcommit: f3937681c3f6e310355071e1842967695e365751
#ms.translationtype: HT
#ms.contentlocale: zh-CN
#ms.lasthandoff: 10/29/2021
#ms.locfileid: "130761788"
parameters:
  buildConfiguration: Release
steps:
- task: DotNetCoreCLI@2
  displayName: Build the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: build
    arguments: --no-restore --configuration ${{ parameters.buildConfiguration }}
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Publish the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: --no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}
    zipAfterPublish: true